# Generated by Django 3.0.8 on 2020-07-19 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_clientes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clientes',
            new_name='Cliente',
        ),
    ]
