# Generated by Django 3.0.8 on 2020-07-19 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_auto_20200718_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='registros',
            field=models.ManyToManyField(blank=True, related_name='clientes', to='registros.Registro'),
        ),
    ]
