# Generated by Django 3.0.8 on 2020-07-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_auto_20200718_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='comment',
            field=models.CharField(default='Não deixou comentários sobre o estabelecimento.', max_length=300),
        ),
        migrations.AddField(
            model_name='cliente',
            name='grade',
            field=models.IntegerField(default=7),
        ),
    ]
