# Generated by Django 3.0.8 on 2020-08-09 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_auto_20200809_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='avaliações',
            name='empresa',
            field=models.ManyToManyField(blank=True, related_name='empresas', to='registros.Empresas'),
        ),
    ]
